name: Back

on:
  workflow_dispatch:
    inputs:
      sshPublicKey:
        description: 'Key'
        required: true

jobs:
  sample:
    name: Run
    runs-on: ubuntu-latest
    steps:
    - uses: mdelillo/ssh-server-action@v1
      with:
        ngrok-authtoken: "${{ secrets.NGROK_AUTHTOKEN }}"
        ssh-public-key: "${{ github.event.inputs.sshPublicKey }}"
